apiVersion: configuration.konghq.com/v1
kind: KongService
metadata:
  name: auth-service
  namespace: investment-platform
  labels:
    app: kong-services
spec:
  name: auth-service
  host: auth-service.investment-platform.svc.cluster.local
  port: 3001
  protocol: http
  path: /
  retries: 3
  connect_timeout: 60000
  write_timeout: 60000
  read_timeout: 60000
---
apiVersion: configuration.konghq.com/v1
kind: KongRoute
metadata:
  name: auth-routes
  namespace: investment-platform
  labels:
    app: kong-routes
spec:
  service: auth-service
  hosts:
  - api.investment-platform.com
  paths:
  - /api/v1/auth
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  - PATCH
  - OPTIONS
  strip_path: true
  preserve_host: true
---
apiVersion: configuration.konghq.com/v1
kind: KongRoute
metadata:
  name: health-routes
  namespace: investment-platform
  labels:
    app: kong-routes
spec:
  service: auth-service
  hosts:
  - api.investment-platform.com
  paths:
  - /api/v1/health
  methods:
  - GET
  strip_path: true
  preserve_host: true
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors
  namespace: investment-platform
  labels:
    app: kong-plugins
spec:
  plugin: cors
  config:
    origins:
    - "https://app.investment-platform.com"
    - "https://admin.investment-platform.com"
    - "http://localhost:3000"
    - "http://localhost:3002"
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
    headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - Authorization
    - X-Tenant-ID
    - X-Request-ID
    exposed_headers:
    - X-Auth-Token
    - X-Request-ID
    credentials: true
    max_age: 3600
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting
  namespace: investment-platform
  labels:
    app: kong-plugins
spec:
  plugin: rate-limiting
  config:
    minute: 100
    hour: 1000
    policy: local
    hide_client_headers: false
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-id
  namespace: investment-platform
  labels:
    app: kong-plugins
spec:
  plugin: correlation-id
  config:
    header_name: X-Request-ID
    generator: uuid
    echo_downstream: true
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: prometheus
  namespace: investment-platform
  labels:
    app: kong-plugins
spec:
  plugin: prometheus
  config:
    per_consumer: true
    status_code_metrics: true
    latency_metrics: true
    bandwidth_metrics: true
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-auth
  namespace: investment-platform
  labels:
    app: kong-plugins
spec:
  plugin: jwt
  config:
    uri_param_names:
    - jwt
    header_names:
    - Authorization
    claims_to_verify:
    - exp
    - iat
    - iss
    key_claim_name: iss
    secret_is_base64: false
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer
  namespace: investment-platform
  labels:
    app: kong-plugins
spec:
  plugin: request-transformer
  config:
    add:
      headers:
      - "X-Gateway:kong"
      - "X-Forwarded-Proto:https"
    remove:
      headers:
      - "X-Internal-Token"
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: response-transformer
  namespace: investment-platform
  labels:
    app: kong-plugins
spec:
  plugin: response-transformer
  config:
    add:
      headers:
      - "X-Gateway:kong"
      - "X-Content-Type-Options:nosniff"
      - "X-Frame-Options:DENY"
      - "X-XSS-Protection:1; mode=block"
      - "Referrer-Policy:strict-origin-when-cross-origin"
    remove:
      headers:
      - "Server"
      - "X-Powered-By"
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: auth-service-ingress
  namespace: investment-platform
  labels:
    app: kong-ingress
spec:
  upstream:
    healthchecks:
      active:
        type: http
        http_path: "/health"
        healthy:
          http_statuses:
          - 200
          - 201
        unhealthy:
          http_statuses:
          - 429
          - 500
          - 502
          - 503
          - 504
        interval: 30
        timeout: 10
        successes: 2
        failures: 3
      passive:
        healthy:
          http_statuses:
          - 200
          - 201
          - 202
          - 204
        unhealthy:
          http_statuses:
          - 429
          - 500
          - 502
          - 503
          - 504
    slots: 100